export enum paths {
  ROOT = 'admin',
  DASHBOARD = 'dashboard',
  PROFILE = 'profile',
  JOB_POSTING = 'job-postings',
  EDIT_JOB_POSTING = 'edit-job-posting',
  CREATE_COMPANY = 'create-company',
  COMPANY_DETAIL = 'company-detail',
  EDIT_COMPANY = 'edit-company',
  JOB_REQUEST = 'job-requests',
  SEARCH = 'search',
  LOGIN = 'login',
  REPORTING = 'reporting',
  LOGOUT = 'logout',
}
