export const listContentActive = [
  {
    id: 1,
    title: "How to make referrals work for you?",
    type: "Article",
    createdBy: "Zoe Leung",
    lastModifiedBy: "Zoe Leung",
    status: "Draft",
    publishDate: new Date("4/25/2024"),
    endDate: new Date("5/15/2024"),
  },
  {
    id: 2,
    title: "The referrals market",
    type: "Article",
    createdBy: "Zoe Leung",
    lastModifiedBy: "William Chung",
    status: "Reviewed",
    publishDate: new Date("5/30/2024"),
    endDate: new Date("5/20/2024"),
  },
  {
    id: 3,
    title: "The state of employees using referrals",
    type: "Article",
    createdBy: "Zoe Leung",
    lastModifiedBy: "Zoe Leung",
    status: "Draft",
    publishDate: new Date("5/30/2024"),
    endDate: new Date("5/20/2024"),
  },
  {
    id: 4,
    title: `Reaching out for help. Don't be afraid`,
    type: "Article",
    createdBy: "Zoe Leung",
    lastModifiedBy: "Zoe Leung",
    status: "Approved",
    publishDate: new Date("5/30/2024"),
    endDate: new Date("5/20/2024"),
  },

  {
    id: 5,
    title: "The success of referrals marketplaces",
    type: "Article",
    createdBy: "Zoe Leung",
    lastModifiedBy: "Zoe Leung",
    status: "Draft",
    publishDate: new Date("5/30/2024"),
    endDate: new Date("5/20/2024"),
  },
];
